-- liquibase formatted sql

-- changeset developer:2 validCheckSum:ANY
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'tm_features';

CREATE TABLE tm_features
(
    feature_id   INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    created_by   INTEGER,
    updated_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by   INTEGER,
    feature_key  VARCHAR(100)                              NOT NULL,
    feature_name VARCHAR(255)                              NOT NULL,
    description  TEXT,
    CONSTRAINT pk_tm_features PRIMARY KEY (feature_id)
);

ALTER TABLE tm_features
    ADD CONSTRAINT uc_tm_features_feature_key UNIQUE (feature_key);

CREATE TABLE tm_role_features
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    created_by INTEGER,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    updated_by INTEGER,
    role_id    INTEGER                                   NOT NULL,
    feature_id INTEGER                                   NOT NULL,
    can_view   BOOLEAN                     DEFAULT FALSE NOT NULL,
    can_create BOOLEAN                     DEFAULT FALSE NOT NULL,
    can_edit   BOOLEAN                     DEFAULT FALSE NOT NULL,
    can_delete BOOLEAN                     DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_tm_role_features PRIMARY KEY (id)
);

ALTER TABLE tm_role_features
    ADD CONSTRAINT uc_tm_role_features_role_feature UNIQUE (role_id, feature_id);

ALTER TABLE tm_role_features
    ADD CONSTRAINT FK_TM_ROLE_FEATURES_ON_ROLE FOREIGN KEY (role_id) REFERENCES tm_roles (role_id) ON DELETE CASCADE;

ALTER TABLE tm_role_features
    ADD CONSTRAINT FK_TM_ROLE_FEATURES_ON_FEATURE FOREIGN KEY (feature_id) REFERENCES tm_features (feature_id) ON DELETE CASCADE;

-- Insert System Features
INSERT INTO tm_features (feature_id, feature_key, feature_name, description)
VALUES
    (1, 'catalog', 'Manage Catalog', 'Menu items, products, photos, and catalog configurations'),
    (2, 'category', 'Manage Categories', 'Menu categories management'),
    (3, 'table', 'Manage Tables', 'Restaurant tables and QR codes'),
    (4, 'voucher', 'Manage Vouchers', 'Discount and promo vouchers'),
    (5, 'promotion', 'Manage Promotions', 'Marketing banners and promotional campaigns'),
    (6, 'barista', 'Manage Baristas', 'Barista and staff account management'),
    (7, 'order', 'Incoming Orders', 'Incoming orders queue and transaction statuses'),
    (8, 'inventory', 'Inventory Status', 'Product inventory and menu item availability'),
    (9, 'report', 'Analytics Overview', 'Sales summary and analytics reports'),
    (10, 'role_management', 'Role Management', 'Configure roles and dynamic feature permissions matrix')
ON CONFLICT (feature_id) DO NOTHING;

-- Insert Default Admin (Role 1) Permissions - Full Access on all features
INSERT INTO tm_role_features (role_id, feature_id, can_view, can_create, can_edit, can_delete)
VALUES
    (1, 1, TRUE, TRUE, TRUE, TRUE),
    (1, 2, TRUE, TRUE, TRUE, TRUE),
    (1, 3, TRUE, TRUE, TRUE, TRUE),
    (1, 4, TRUE, TRUE, TRUE, TRUE),
    (1, 5, TRUE, TRUE, TRUE, TRUE),
    (1, 6, TRUE, TRUE, TRUE, TRUE),
    (1, 7, TRUE, TRUE, TRUE, TRUE),
    (1, 8, TRUE, TRUE, TRUE, TRUE),
    (1, 9, TRUE, TRUE, TRUE, TRUE),
    (1, 10, TRUE, TRUE, TRUE, TRUE)
ON CONFLICT (role_id, feature_id) DO NOTHING;

-- Insert Default Barista (Role 3) Permissions
INSERT INTO tm_role_features (role_id, feature_id, can_view, can_create, can_edit, can_delete)
VALUES
    (3, 1, TRUE, FALSE, FALSE, FALSE),
    (3, 7, TRUE, FALSE, TRUE, FALSE),
    (3, 8, TRUE, FALSE, TRUE, FALSE),
    (3, 9, TRUE, FALSE, FALSE, FALSE)
ON CONFLICT (role_id, feature_id) DO NOTHING;

-- Insert Default User (Role 2) Permissions
INSERT INTO tm_role_features (role_id, feature_id, can_view, can_create, can_edit, can_delete)
VALUES
    (2, 1, TRUE, FALSE, FALSE, FALSE),
    (2, 2, TRUE, FALSE, FALSE, FALSE),
    (2, 3, TRUE, FALSE, FALSE, FALSE),
    (2, 4, TRUE, FALSE, FALSE, FALSE),
    (2, 5, TRUE, FALSE, FALSE, FALSE)
ON CONFLICT (role_id, feature_id) DO NOTHING;

-- rollback DROP TABLE tm_role_features CASCADE;
-- rollback DROP TABLE tm_features CASCADE;
